services:
  backend:
    build:
      context: ./Task/task
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      ENVIRONMENT_ENGINE: django.db.backends.postgresql
      POSTGRES_DB: jenia
      POSTGRES_USER: jenia
      POSTGRES_PASSWORD: 12345678
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: jenia
      POSTGRES_USER: jenia
      POSTGRES_PASSWORD: 12345678

  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"