# Generated by Django 5.1.3 on 2024-11-18 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_projects',
        ),
        migrations.AddField(
            model_name='user',
            name='user_projects',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
