# Generated by Django 5.1.3 on 2024-11-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
        ('users', '0002_remove_user_user_projects_user_user_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_projects',
        ),
        migrations.AddField(
            model_name='user',
            name='user_projects',
            field=models.ManyToManyField(related_name='projects', to='main.project'),
        ),
    ]
