# Generated by Django 5.1.3 on 2024-11-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar_remove_user_user_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='None/default_avatar.png', null=True, upload_to='avatars/'),
        ),
    ]
