# Generated by Django 5.1.3 on 2024-11-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_user_all_projects_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_all_projects',
            field=models.TextField(null=True),
        ),
    ]
