# Generated by Django 4.2.11 on 2024-11-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_user_all_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_all_projects',
        ),
    ]
